In [6]:
import pandas as pd
df_customers=pd.read_csv('customers.csv')
df_customers

   customer_id first_name last_name        city  age            email
0            1      Ahmed    Hassan       Cairo   25  ahmed@email.com
1            2       Sara       Ali        Giza   31   sara@email.com
2            3       Omar   Mohamed       cairo   17   omar@email.com
3            4       Mona   Ibrahim  Alexandria   28              NaN
4            5      Ahmed    Hassan       Cairo   25  ahmed@email.com

In [7]:
columns_list=df_customers.columns

In [8]:
columns_list

Index(['customer_id', 'first_name', 'last_name', 'city', 'age', 'email'], dtype='object')

In [9]:
for i in columns_list:
    print(df_customers[i].dtype)

int64
object
object
object
int64
object

In [10]:
df_customers_cleaned = df_customers.copy()
df_customers_cleaned['email']=df_customers_cleaned['email'].fillna("No Email attached")
df_customers_cleaned.drop_duplicates()
df_customers_cleaned['city']=df_customers_cleaned['city'].str.strip().str.upper()
df_customers_cleaned['Full_Name']=df_customers_cleaned['first_name']+" "+df_customers_cleaned['last_name']
df_customers_cleaned

,customer_id,first_name,last_name,city,age,email,Full_Name
0,1,Ahmed,Hassan,CAIRO,25,ahmed@email.com,Ahmed Hassan
1,2,Sara,Ali,GIZA,31,sara@email.com,Sara Ali
2,3,Omar,Mohamed,CAIRO,17,omar@email.com,Omar Mohamed
3,4,Mona,Ibrahim,ALEXANDRIA,28,No Email attached,Mona Ibrahim
4,5,Ahmed,Hassan,CAIRO,25,ahmed@email.com,Ahmed Hassan

In [11]:
import requests
import pandas as pd
url='https://raw.githubusercontent.com/MohammedHameds/test1455/refs/heads/main/products.csv'
response=requests.get(url)
df_API=pd.read_csv(url)
df_API

c:\Users\mohamed\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.4.3)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(

   product_id product_name     category  unit_price
0         101       Laptop  Electronics       25000
1         102        Mouse  Accessories         500
2         103     Keyboard  Accessories        1200
3         104      Monitor  Electronics        7000
4         105   Headphones  Accessories        2500
5         106       Webcam  Accessories        1800

In [12]:
df_API_cleaned=df_API.copy()
columns_api=df_API_cleaned.columns
columns_api

Index(['product_id', 'product_name', 'category', 'unit_price'], dtype='object')

In [13]:
for i in columns_api:
    print(df_API_cleaned[i].dtype)

int64
object
object
int64

In [14]:
df_API_cleaned=df_API_cleaned.drop_duplicates()
df_API_cleaned['unit_price']=pd.to_numeric(df_API_cleaned['unit_price'],errors='coerce')
df_API_cleaned

   product_id product_name     category  unit_price
0         101       Laptop  Electronics       25000
1         102        Mouse  Accessories         500
2         103     Keyboard  Accessories        1200
3         104      Monitor  Electronics        7000
4         105   Headphones  Accessories        2500
5         106       Webcam  Accessories        1800

In [15]:
for i in columns_api:
    print(df_API_cleaned[i].dtype)

int64
object
object
int64

In [16]:
df_API_cleaned['product_name']=df_API_cleaned['product_name'].str.strip().str.title()
df_API_cleaned['category']=df_API_cleaned['category'].str.strip().str.title()
df_API_cleaned

   product_id product_name     category  unit_price
0         101       Laptop  Electronics       25000
1         102        Mouse  Accessories         500
2         103     Keyboard  Accessories        1200
3         104      Monitor  Electronics        7000
4         105   Headphones  Accessories        2500
5         106       Webcam  Accessories        1800

In [17]:
pip install pyarrow

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pyarrow in c:\users\mohamed\appdata\local\programs\python\python310\lib\site-packages (25.0.1)

In [18]:
import pandas as pd
df_orders = pd.read_parquet("orders.parquet")
df_orders

    order_id  customer_id  product_id  quantity order_date
0       1001            1         101         2 2026-09-01
1       1002            2         102         1 2026-09-01
2       1003            3         103         3 2026-09-02
3       1004            4         101         1 2026-09-02
4       1005            1         104         2 2026-09-03
5       1006            5         102         1 2026-09-03
6       1007            2         105         4 2026-09-04
7       1008            3         101         1 2026-09-04
8       1009            4         103         2 2026-09-05
9       1010            1         104         1 2026-09-05
10      1003            3         103         3 2026-09-02

In [19]:
df_orders=df_orders.drop_duplicates()

In [20]:
df_orders

   order_id  customer_id  product_id  quantity order_date
0      1001            1         101         2 2026-09-01
1      1002            2         102         1 2026-09-01
2      1003            3         103         3 2026-09-02
3      1004            4         101         1 2026-09-02
4      1005            1         104         2 2026-09-03
5      1006            5         102         1 2026-09-03
6      1007            2         105         4 2026-09-04
7      1008            3         101         1 2026-09-04
8      1009            4         103         2 2026-09-05
9      1010            1         104         1 2026-09-05

In [21]:
orders_columns=df_orders.columns

In [22]:
for i in orders_columns:
    print(df_orders[i].dtype)

int64
int64
int64
int64
datetime64[us]

In [23]:
df_orders['order_date']=pd.to_datetime(df_orders['order_date'], errors='coerce')

C:\Users\mohamed\AppData\Local\Temp\ipykernel_14476\4172662051.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_orders['order_date']=pd.to_datetime(df_orders['order_date'], errors='coerce')

In [24]:
df_orders['order_date']

0   2026-09-01
1   2026-09-01
2   2026-09-02
3   2026-09-02
4   2026-09-03
5   2026-09-03
6   2026-09-04
7   2026-09-04
8   2026-09-05
9   2026-09-05
Name: order_date, dtype: datetime64[us]

In [25]:
customer_API_merged=pd.merge(df_orders,df_API_cleaned,on='product_id')
total_merged=pd.merge(customer_API_merged,df_customers_cleaned,on='customer_id')
total_merged

,order_id,customer_id,product_id,quantity,order_date,product_name,category,unit_price,first_name,last_name,city,age,email,Full_Name
0,1001,1,101,2,2026-09-01,Laptop,Electronics,25000,Ahmed,Hassan,CAIRO,25,ahmed@email.com,Ahmed Hassan
1,1002,2,102,1,2026-09-01,Mouse,Accessories,500,Sara,Ali,GIZA,31,sara@email.com,Sara Ali
2,1003,3,103,3,2026-09-02,Keyboard,Accessories,1200,Omar,Mohamed,CAIRO,17,omar@email.com,Omar Mohamed
3,1004,4,101,1,2026-09-02,Laptop,Electronics,25000,Mona,Ibrahim,ALEXANDRIA,28,No Email attached,Mona Ibrahim
4,1005,1,104,2,2026-09-03,Monitor,Electronics,7000,Ahmed,Hassan,CAIRO,25,ahmed@email.com,Ahmed Hassan
5,1006,5,102,1,2026-09-03,Mouse,Accessories,500,Ahmed,Hassan,CAIRO,25,ahmed@email.com,Ahmed Hassan
6,1007,2,105,4,2026-09-04,Headphones,Accessories,2500,Sara,Ali,GIZA,31,sara@email.com,Sara Ali
7,1008,3,101,1,2026-09-04,Laptop,Electronics,25000,Omar,Mohamed,CAIRO,17,omar@email.com,Omar Mohamed
8,1009,4,103,2,2026-09-05,Keyboard,Accessories,1200,Mona,Ibrahim,ALEXANDRIA,28,No Email attached,Mona Ibrahim
9,1010,1,104,1,2026-09-05,Monitor,Electronics,7000,Ahmed,Hassan,CAIRO,25,ahmed@email.com,Ahmed Hassan

In [26]:
total_merged.drop('first_name',axis=1,inplace=True)
total_merged.drop('last_name',axis=1,inplace=True)

In [27]:
total_merged[['Full_Name','age','city','email','customer_id','product_id','product_name','category','order_id','order_date','unit_price','quantity']]

,Full_Name,age,city,email,customer_id,product_id,product_name,category,order_id,order_date,unit_price,quantity
0,Ahmed Hassan,25,CAIRO,ahmed@email.com,1,101,Laptop,Electronics,1001,2026-09-01,25000,2
1,Sara Ali,31,GIZA,sara@email.com,2,102,Mouse,Accessories,1002,2026-09-01,500,1
2,Omar Mohamed,17,CAIRO,omar@email.com,3,103,Keyboard,Accessories,1003,2026-09-02,1200,3
3,Mona Ibrahim,28,ALEXANDRIA,No Email attached,4,101,Laptop,Electronics,1004,2026-09-02,25000,1
4,Ahmed Hassan,25,CAIRO,ahmed@email.com,1,104,Monitor,Electronics,1005,2026-09-03,7000,2
5,Ahmed Hassan,25,CAIRO,ahmed@email.com,5,102,Mouse,Accessories,1006,2026-09-03,500,1
6,Sara Ali,31,GIZA,sara@email.com,2,105,Headphones,Accessories,1007,2026-09-04,2500,4
7,Omar Mohamed,17,CAIRO,omar@email.com,3,101,Laptop,Electronics,1008,2026-09-04,25000,1
8,Mona Ibrahim,28,ALEXANDRIA,No Email attached,4,103,Keyboard,Accessories,1009,2026-09-05,1200,2
9,Ahmed Hassan,25,CAIRO,ahmed@email.com,1,104,Monitor,Electronics,1010,2026-09-05,7000,1

In [28]:
total_merged["total_amount"] = total_merged["quantity"] * total_merged["unit_price"]
total_merged

,order_id,customer_id,product_id,quantity,order_date,product_name,category,unit_price,city,age,email,Full_Name,total_amount
0,1001,1,101,2,2026-09-01,Laptop,Electronics,25000,CAIRO,25,ahmed@email.com,Ahmed Hassan,50000
1,1002,2,102,1,2026-09-01,Mouse,Accessories,500,GIZA,31,sara@email.com,Sara Ali,500
2,1003,3,103,3,2026-09-02,Keyboard,Accessories,1200,CAIRO,17,omar@email.com,Omar Mohamed,3600
3,1004,4,101,1,2026-09-02,Laptop,Electronics,25000,ALEXANDRIA,28,No Email attached,Mona Ibrahim,25000
4,1005,1,104,2,2026-09-03,Monitor,Electronics,7000,CAIRO,25,ahmed@email.com,Ahmed Hassan,14000
5,1006,5,102,1,2026-09-03,Mouse,Accessories,500,CAIRO,25,ahmed@email.com,Ahmed Hassan,500
6,1007,2,105,4,2026-09-04,Headphones,Accessories,2500,GIZA,31,sara@email.com,Sara Ali,10000
7,1008,3,101,1,2026-09-04,Laptop,Electronics,25000,CAIRO,17,omar@email.com,Omar Mohamed,25000
8,1009,4,103,2,2026-09-05,Keyboard,Accessories,1200,ALEXANDRIA,28,No Email attached,Mona Ibrahim,2400
9,1010,1,104,1,2026-09-05,Monitor,Electronics,7000,CAIRO,25,ahmed@email.com,Ahmed Hassan,7000

In [29]:
sales=total_merged[['order_id','Full_Name','customer_id','product_name','product_id','quantity','unit_price','total_amount']]

sales

,order_id,Full_Name,customer_id,product_name,product_id,quantity,unit_price,total_amount
0,1001,Ahmed Hassan,1,Laptop,101,2,25000,50000
1,1002,Sara Ali,2,Mouse,102,1,500,500
2,1003,Omar Mohamed,3,Keyboard,103,3,1200,3600
3,1004,Mona Ibrahim,4,Laptop,101,1,25000,25000
4,1005,Ahmed Hassan,1,Monitor,104,2,7000,14000
5,1006,Ahmed Hassan,5,Mouse,102,1,500,500
6,1007,Sara Ali,2,Headphones,105,4,2500,10000
7,1008,Omar Mohamed,3,Laptop,101,1,25000,25000
8,1009,Mona Ibrahim,4,Keyboard,103,2,1200,2400
9,1010,Ahmed Hassan,1,Monitor,104,1,7000,7000

In [ ]:
output=list(sales.itertuples(name=None, index=None))
output

In [31]:
import pyodbc
conn=pyodbc.connect(
    "driver={ODBC Driver 17 for SQL Server};"
    "Server=DESKTOP-1TM1TG3\SQLEXPRESS;"
    "Database=mohamed_Ramadan_DB;"
    "Trusted_Connection=yes;"    ## winodw authentication
)
cursor=conn.cursor()

In [32]:
SQL_query1='''
create table Sales(
order_id varchar(50),
Full_Name varchar(50),
customer_id varchar(50),
product_name varchar(50),
product_id varchar(50),
quantity varchar(50),
unit_price varchar(50),
total_amount varchar(50),
) 

'''
cursor.execute(SQL_query1)

In [35]:
SQL_query2='insert into Sales values (?,?,?,?,?,?,?,?)'
cursor.executemany(SQL_query2,output)

In [37]:
cursor.commit()
conn.close()

['SQL Server',
 'ODBC Driver 17 for SQL Server',
 'ODBC Driver 18 for SQL Server',
 'Microsoft Access Driver (*.mdb, *.accdb)',
 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)',
 'Microsoft Access Text Driver (*.txt, *.csv)',
 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']